### ISSUE TITLE
Use prefix.cc to ensure that all apps use the same prefix for ontologies

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/activitypods#128]
We can do a GET like this: http://prefix.cc/?q=http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2Fname

And in the `Location` header, we will have the prefix: `http://prefix.cc/foaf:name`

Or we can parse http://prefix.cc/context but we will need to do it every time as a prefix can have been added just recently.

**Comment by Laurin-W** [comment]
In general, I like the idea.
Two things though:
1. The site's TLS is not properly configures which indicates poor maintenance and could lead to issues.
2. Since items are votable, this will not guarantee deterministic results over time which could cause trouble as well.

Do you think that's a problem in practice?

**Comment by srosset81** [comment]
The [LOV](https://lov.linkeddata.es/dataset/lov/) website seems better maintained and it has an API, but it's more difficult to add a new ontology, while with prefix.cc it can be done within minutes. I think it's important to make it easy to add ontologies, otherwise applications won't be able to register.

For ActivityPods, we will use prefix.cc only when applications register classes from unknown ontologies. But after the app registration, the prefix will be saved (on the settings database) and prefix.cc won't be queried again. Applications will use the TypeIndex to know what is the URL of the container.

Two other alternatives:
- We could create our own database of prefixes. But this is a lot of maintainance, and what rules do we apply to accept new proposals ?
- Applications could declare their favorite prefixes when registering on the pod. This was the option I initially preferred, but then I thought it could create conflicts. At least with prefix.cc we can be sure that common ontologies prefixes will not change so easily.

**Comment by Laurin-W** [comment]
> We could create our own database of prefixes. But this is a lot of maintainance

Totally that this is probably out of scope :)

> -   Applications could declare their favorite prefixes when registering on the pod. This was the option I initially preferred, but then I thought it could create conflicts.

I see..

Thanks for the clarifications :)
