### ISSUE TITLE
Allow to delete Pod account from Pod frontend

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/activitypods#135]
Since v1.4 and [this PR](https://github.com/assemblee-virtuelle/activitypods/pull/56), an actor can send an activity to his/her contacts to ask them to delete all his/her data. But there is no mechanism to actually send this activity.

To complete this task, we need:

- Add a button in some "danger zone" which send this `Offer > Delete > WebID` activity
  - Send it to all contacts or to all people who can see the user's profile ?
- Disconnect the user and maybe prevent him/her to connect again
  - Maybe delete right away the account in the `settings` dataset, or change the password hash, or set the account as closed ?
  - It could be useful to block the account (for several months or forever ?), so that no user can take this same identity ?
- Schedule a deletion of the account maybe 24 hours later, so that all contacts have the time to receive and process the request
  - If the user is deleted immediately, others will not be able to check his/her HTTP signature 
- Manually delete the dataset on the filesystem, because we can't use Fuseki API for that
  - See https://github.com/assemblee-virtuelle/semapps/issues/871 
  - A `delete` action could be added to the `triplestore.dataset` service, which will do a "raw deletion" if the dataset is secure, and a deletion through Fuseki API if it is not.
  - Ensure this raw deletion doesn't affect negatively Fuseki, and that no restart is required (hopefully not)

This could be inspiring: https://codeberg.org/fediverse/fep/src/branch/main/fep/7628/fep-7628.md

**Comment by Laurin-W** [comment]
TODOs:
- [ ] Create delete service for the main method
- [ ] Delete actions:
  - [ ] delete key (will remove rsa fs key, may be in `/old` dir)
  - [ ] Create `auth.account.deleteByWebId` method
  - [ ] fuseki `DELETE $/datasets/<dataset>` (for secure datasets, see https://github.com/assemblee-virtuelle/semapps/issues/871)
  - [ ] delete uploads
  - [ ] delete backup files
  - [ ] send delete activity? (see https://github.com/assemblee-virtuelle/activitypods/issues/135)
    - [ ] if we do that, we might need to retain the account (or at least the webId) a bit, for others to check the publicKey
- [ ] retain the user name to block new account creation for some time (maybe this should be optional)
- [ ] proposed route: `DELETE /.management/pod/<dataset>` or @srosset81 do you think we should just require the activity `Offer > Delete > WebID` activity to be sent to the outbox?  
- [ ] require `iKnowWhatImDoing` param in critical methods
- [ ] documentation
- [ ] check, if fuseki is able to create a new dataset after delete
- [ ] do we have a scheduler?
- [ ] Maybe require an email confirmation to delete account

**Comment by Laurin-W** [comment]
linking https://github.com/assemblee-virtuelle/activitypods/issues/211
