### ISSUE TITLE
Allow to export all Pod data from Pod frontend

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/activitypods#136]
The easiest may be to generate a backup through Jena Fuseki (there is a `triplestore.dataset.backup` action for that), and then send the generated backup to the user.

**Comment by Laurin-W** [comment]
TODOs:

- [ ] trigger on route `.management/backup/<dataset>`
- [ ] zip all uploads (and hash  or encode the URIs as file names) @srosset81 do you have a preference? Maybe something readable might be better for people to inspect
- [ ] add fuseki backup to zip
- [ ] if key service not migrated, add rsa key to zip file
- [ ] anything missing?

I checked the time for fuseki backups to be created, the largest dataset took about 10s to backup. I think as long as this does not increase significantly, it's fine to not set up an async mechanism to query the progress. What do you think, @srosset81?

**Comment by Laurin-W** [comment]
Closing in favor of #228
