### ISSUE TITLE
Invitation links: redirect to profile if we are already connected

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/activitypods#139]
If I follow an invitation link but I'm already connected with the person, I should be redirected to its profile, maybe with a notification like "You are already connected with XXX"

**Comment by Laurin-W** [comment]
Do you think, we should take care of the case that the invited user has the inviter's profile in their list but the inviter might not? I.e. should the invited person send an `Accept > Offer > Profile` to the inviter anyways?

**Comment by srosset81** [comment]
Yes, that's a good idea !
