### ISSUE TITLE
Circles management

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/activitypods#27]
- Add a new "Circle" class (`as:Group`) which allows to group contacts together
  - Circles are only visible by the owner of the pod. They are not used outside.
- Allow to select a Circle on the Share dialog: this will select all people who are part of this circle
- Allow to create a Circle, and add people to it, in the "My network" page (design needed)

**Comment by Laurin-W** [comment]
Closing this, since it is implemented in the [Groups](https://github.com/assemblee-virtuelle/activitypods/pull/77) feature now :)
