### ISSUE TITLE
Where can I find the endpoint for the Solid APIs?

### ISSUE THREAD

**Issue by phochste** [assemblee-virtuelle/activitypods#53]
I'm just came across your project and I'm very interested how the Solid and ActivityPub can work together. I've created a new pod at MyPod.store. Is there some information where I can find the Solid API endpoints for this pod?

**Comment by srosset81** [comment]
Hello
When you create a POD, your WebID is at https://podprovider.com/username
The data can then be found on https://podprovider.com/username/data (a predicate is missing)
This is then a standard [Linked Data Plateform](https://www.w3.org/TR/ldp-primer/) API. There are some bugs with the Turtle format, it's better to use JSON-LD.
If you have other questions, we would be glad to answer them on [this chatroom](https://chat.lescommuns.org/channel/activitypods), which is more appropriate than Github issues.
