### ISSUE TITLE
Add default address in profil edition

### ISSUE THREAD

**Issue by Alice-Po** [assemblee-virtuelle/activitypods#59]
![image](https://user-images.githubusercontent.com/61314813/230618524-fa011af5-8b17-412a-974a-42d31aa324e6.png)
Maybe it would be cool to choose in a select field between the ones we have in setting.

**Comment by sumitshinde-84** [comment]
i would like to work  on this issue

**Comment by srosset81** [comment]
@sumitshinde-84 That would be great ! Do you know React-Admin already ?
To get you started, you only need to look for the [ReferenceInput](https://semapps.org/docs/frontend/input-components#referenceinput).
If you have questions, feel free to join our [chatroom](https://chat.lescommuns.org/channel/activitypods), I'm available there most of the time.

**Comment by srosset81** [comment]
Done and deployed

**Comment by sumitshinde-84** [comment]
> To get you started,

I am proficient in React and Next.js, and I am familiar with backend development.

**Comment by srosset81** [comment]
@sumitshinde-84 Great !
This issue is done, but if you want you can do https://github.com/assemblee-virtuelle/activitypods/issues/60 which is quite similar.
I'm still available on our [chatroom](https://chat.lescommuns.org/channel/activitypods) if you have questions or want to make a call.
