### ISSUE TITLE
Implement password validation for signup form.

### ISSUE THREAD

**Issue by Laurin-W** [assemblee-virtuelle/activitypods#75]
Right now, there are no minimum requirements for user passwords.
A set of enforced rules (at least for the frontend) would be nice, to make password guessing harder.

**Comment by srosset81** [comment]
Yes I agree. But maybe not something too strong, otherwise users end up forgetting their password.
What would you suggest ?

**Comment by Laurin-W** [comment]
That's a good point! I bet there is some research on this. I'll take a look :)

**Comment by Laurin-W** [comment]
Alright, so I had a look at three tools which might help:

1. https://cups.cs.cmu.edu/meter2/ this tool is based on a usability study (github repo: https://github.com/cupslab/password_meter)
   The tool looks really nice and most solid but has two downsides: First, the dictionary data it uses to check strength is a couble of MBs in size. It's probably ok to exclude a fair amount of that thoug. The other issue is that it might take more time to implement in the application since from my first look the frontend and logic seemed to be a bit too coupled.
2. Then we have https://www.npmjs.com/package/zxcvbn maintained by dropbox. It seems quite similar to the first but comes as a library. It's still a couple hundred kB, so it shouldn't go in a bundle at least.
3. This one is very light-weight: https://www.npmjs.com/package/password-strength-score (2kB) but not very complex in regard to dictionary checks and so on.

What do you think is decent here?

**Comment by srosset81** [comment]
`password-strength-score` looks good enough for me. It's customizable enough for our needs.
