### ISSUE TITLE
Can not signup on mypod.store

### ISSUE THREAD

**Issue by Potherca** [assemblee-virtuelle/activitypods#76]
Hi! Not sure if I shoud report this here, so please direct me elsewhere if I am in the wrong place.

I wanted to play around with ActivityPods but when I tried to register a pod on mypod.store I got an error:

![image](https://github.com/assemblee-virtuelle/activitypods/assets/195757/e3d68ab3-dc38-49f1-977e-7ef5d05926a3)

```json
{
    "name": "FetchError",
    "message": "request to http://fuseki:3030/settings/query failed, reason: getaddrinfo EAI_AGAIN fuseki",
    "code": "EAI_AGAIN",
    "type": "system"
}
```

**Comment by srosset81** [comment]
Thanks for this report. Yesterday I installed another software on the same server as mypod.store and there wasn't enough memory left for Fuseki (the triplestore, ie. semantic database), which crashed. I've restarted it, and it should be fine now.
