### ISSUE TITLE
Make the backend work with Node v20

### ISSUE THREAD

**Issue by Lawhacknifemi** [assemblee-virtuelle/activitypods#79]
I tried building the boilerplate on node 20.5.1 . I had to downgrade to node 14.17.3 . The issue is with node-gyp which keeps saying it requires a C++ build tool for it to build, even after having that installed. By the way, this is a known issue, You can check `[here](https://github.com/nodejs/help/issues/3928)` for reference. 

While I understand that this is not entirely activitypods issue, I think it will be more significant to put potential issues on the docs, which will help people find their way around issues quite easily.

Build Environment: Windows 11

**Comment by srosset81** [comment]
Thanks. Currently we use Node v16, but we must indeed make it compatible with v20.

**Comment by srosset81** [comment]
The [v2.0](https://github.com/assemblee-virtuelle/activitypods/pull/106) will work only on Node v20, because it is required by the `node-oidc-provider` package we use.
